name: Build and deploy

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - master
  # trigger after successful scrape, as push from scrape action doesn't trigger a push event
  workflow_run:
    workflows: ["Scrape official timetable"]
    types:
      - completed

# Checkout branch and comment on PR
permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      # NOTE - THIS CHECKOUT MAY CONTAIN UNTRUSTED CODE
      # TO AVOID SECRET DISCLOSURE, IT MUST ONLY RUN IN THE SANDBOXED AZURE BUILD ENVIRONMENT
      - name: Checkout from PR
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build and deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # GitHub bot comments only, not available to code
          action: upload
          app_location: . # Root
          app_artifact_location: build # Build artifacts
          api_location: api # Functions
        env:
          REACT_APP_INSIGHTS_STRING: ${{ secrets.REACT_APP_INSIGHTS_STRING }}